<a href="https://colab.research.google.com/github/Jok-truong/100-Days-Of-ML-Code/blob/master/chapter_1_the_building_blocks_scalars_vectors_and_matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Chapter 1: The Building Blocks: Scalars, Vectors, and Matrices**


1. Mục tiêu:
    - Hiểu về **các đối tượng cơ bản của đại số tuyến tính (linear algebra)** dùng trong Machine Learning.
    - Hiểu cách **biểu diễn dữ liệu dưới dạng toán học** trước khi sử dụng thuật toán hoặc mô hình.

2. Ba thành phần chính cơ bản trong **Linear Algebra**:
    - **Scalar**:
        - Một số đơn lẻ. VD: 5, 3.14
    - **Vector**
        - Danh sách các số có thứ tự
        - Dùng để biểu diễn **một điểm trong không gian** hoặc **một sample dữ liệu** với nhiều feature.
    - **Matrix**:
        - Bảng (grid) gồm nhiều số.
        - Dùng để **tổ chức nhiều vector dữ liệu thành một dataset**.

3. Cách biểu diễn dữ liệu trong Machine Learning:
    - Một **sample dữ liệu** -> biểu diễn bằng **vector `[x1, x2, x3]`**
    - Nhiều sample dữ liệu -> tạo thành **data matrix**

## **#1: Why Linear Algebra for Machine Learning?**

- Machine Learning là quá trình **tìm ra các pattern trong dữ liệu**. Tuy nhiên, để máy tính có thể xử lý thông tin - dù đó là **đánh giá của khách hàng, giá cổ phiếu, hay một bức ảnh con chó** - thì thông tin đó trước hết phải được **chuyển thành dạng số**.

- **Linear Algebra** chính là **"ngữ pháp" trong ngôn ngữ số này**. Nó cung cấp một tập công cụ mạnh và hiệu quả để **tổ chức và thao tác con số**, vì vậy nó trở thành **nền tảng tính toán cho hầu hết các mô hình Machine Learning**.

<p align="center">
  <img src="../../Images/Gemini_Generated_Image_phiejpphiejpphie.png" alt="Gemini_Generated_Image_phiejpphiejpphie.png"/>
</p>

### **1. Representing Data as Numbers**

- Trước khi một thuật toán có thể học, chúng ta cần một cách có **hệ thống để tổ chức dữ liệu**.

- VD: Dự đoán giá nhà, thông tin của một căn nhà có thể gồm:
    - Diện tích: `1500 sq.ft`
    - Số phòng ngủ: `3`
    - Tuổi của nhà: `20 năm`
    
    => Chúng ta có thể biểu diễn căn nhà này dưới dạng một **vector**:

<p align="center">
$house_{vector} = \begin{bmatrix}
  1500 ,
  3 ,
  20
\end{bmatrix}$</p>

- Vector này không chỉ ở dạng **danh sách số**. Nó còn có thể được hiểu là **một điểm trong không gian ba chiều** trong đó mỗi chiều tương ưng với **một feature**:

- Ta có thể có một căn nhà khác và cũng có:
    - 2100 sq.ft
    - 4 phòng ngủ
    - 5 năm tuổi
    
    => Và ta sẽ có một **vector** của một căn nhà khác:

<p align="center">
$\begin{bmatrix}
  2100 ,
  4 ,
  5
\end{bmatrix}$</p>

- Khi chúng ta thu thập data của **hàng nghìn căn nhà**, các **vector** này có thể được **xếp chồng lên nhau tạo thành một bảng số**. Và ta gọi bảng này là **matrix**.

<p align="center">
$house_{vector} = \begin{bmatrix}
  1500 & 3 & 20  \\
  2100  & 4 & 5\\
  1800 & 3 & 10 \\
  ... & ... & ..
\end{bmatrix}$
 </p>

- Trong **matrix** này có:
    - Mỗi **hàng (row)** - một **căn nhà (sample)**
    - Mỗi **cột (column)** - một **đặc trưng (feature)**
    

- **Matrix** này trở thành **một đối tượng chính mà mô hình Machine Learning sẽ  làm việc.**

<p align="center">
  <img src="../../Images/cc5b9578-8346-4519-ba5d-ed7534bcebd0.png" alt="cc5b9578-8346-4519-ba5d-ed7534bcebd0.png"/>
</p>

### **2. Computing with Data Efficiently**

- Sau khi data được tổ chức thành **vector và matrix**, chúng ta cần thực hiện các phép tính:
- VD:
    - Điều chỉnh **tham số mô hình (model parameters)**.
    - Tính **similarity** giữa các dối tượng.
    - **Transform dữ liệu** để làm nổi bật các pattern quan trọng



- Nếu **không có Linear algebra**, bạn sẽ phải viết **vòng lặp (loops)** để xử lý từng số một trong **dataset** => Điều này: Rất chậm, không hiệu quả, làm code khó đọc hơn.

In [ ]:
dataset = [[8, 7, 9], [6, 5, 7], [9, 9, 10]]

for i in range(len(dataset)):
    for j in range(len(dataset[i])):
        dataset[i][j] = dataset[i][j] + 1

print(f"dataset: {dataset}")

dataset: [[9, 8, 10], [7, 6, 8], [10, 10, 11]]


- **Linear algebra** cho phép chúng ta **viết một phép toán cho toàn bộ dataset chỉ trong một dòng code**. - VD:
    - **Nhân ma trận (matrix multiplication)** cho phép xử lý **hàng nghìn dữ liệu cùng lúc**

    => Điều này không chỉ là tiện lợi, nó là **lý do khiến Machine Learning hiện đại có thể chạy được trên thực tế.**

In [ ]:
import numpy as np

dataset = [[8, 7, 9], [6, 5, 7], [9, 9, 10]]
matrix = np.array(dataset)

matrix = matrix + 1

print(f"{matrix}")

[[ 9  8 10]
 [ 7  6  8]
 [10 10 11]]


- Các thư viện như NumPy sử dụng các **thư viện toán học cấp thấp (như BLAS/LAPACK) được tối ưu hóa bằng ngôn ngữ C hoặc Fortran**. Chúng **thực hiện phép tính này trên toàn bộ khối dữ liệu cùng lúc thay vì từng số một**

<p align="center">
  <img src="../../Images/Gemini_Generated_Image_q3n1p1q3n1p1q3n1.png" alt="Gemini_Generated_Image_q3n1p1q3n1p1q3n1.png"/>
</p>

### **3. The Blueprint for Machine Learning Models**
- Nhiều thuật toán Machine Learning **không chỉ sử dụng đại số tuyến tính - chúng được định nghĩa cũng vì đại số tuyến tính**.

 #### **3.1 Linear Regression**

 - Bài toán **fit một đường thẳng vào dữ liệu** có thể được viết thành phương trình:
        
    * $A_x = b$ - Trong đó:
        * **$A$ -> ma trân dữ liệu (data matrix)**
        * **$b$ → vector kết quả cần dự đoán (ví dụ: giá nhà)**
        * **$x$ -> vetor tham só của mô hình**
        -> Khi giải được phương trình này rồi, chúng ta sẽ tìm được **các tham số tốt nhất của mô hình**.


#### **3.2 Neural Network**

- **Neural Network** gồm nhiều **layer kết nối với nhau**. Khi dữ liệu đi qua các layer, qua trình này bao gồm: $y = W_x + b$ - trong đó:
    * $𝑥$ → vector dữ liệu đầu vào
    * $𝑊$ → ma trận trọng số
    * $𝑏$ → bias
    * $𝑦$ -> đầu ra

- Sau đó kết quả sẽ đi qua **activation function** - Qua trình này được gọi là **traning neural network** - Thực chất là **tìm các giá trị tốt nhất của ma trân này**

#### **3.3 Principal Component Analysis (PCA)**

- **PCA** là kỹ thuật phổ biến để **giảm số chiều của data (dimensionality reduction)**. Nó tìm các **hướng quan trọng nhất trong data**.

- Các hướng này chính là **eigenvectors của covariance matrix** của data.

<p align="center">
  <img src="../../Images/7300bd4c-6654-4e38-9d3a-1cf8461e0921.png" alt="7300bd4c-6654-4e38-9d3a-1cf8461e0921.png"/>
</p>

### **4. Summary: Why Linear Algebra?**

- **Ngôn ngữ của dữ liệu**: Giúp chuyển đổi thông tin thực tế (hình ảnh, văn bản, âm thanh) thành dạng số mà máy tính có thể hiểu được.
- **Hiệu suất tính toán**: Cho phép thực hiện các phép tính trên hàng triệu điểm dữ liệu cùng lúc thông qua vector hóa (vectorization), thay vì dùng vòng lặp chậm chạp.
- **Nền tảng của các thuật toán**: Các mô hình từ đơn giản như Linear Regression đến phức tạp như Deep Learning đều được xây dựng dựa trên các phép toán ma trận và vector.

## **#2: Scalars: The Simplest Objects**

- **Một giá trị đơn lẻ (A single value represents)** là mảng thông tin cơ bản nhất trong data. Trong **linear algebra** giá trị này được gọi là **scalar**.

- **Scalar** đơn giản chỉ là **một con số bình thường**. Nó có **độ lớn(magnitude)** nhưng **không có hướng (direction)**. Đây là **phần tử dữ liệu đơn giản nhất** dùng trong tính toán.

- VD: Trong đời sống chúng thường gặp **scalar**:
    - Nhiệt độ trong phòng: $20^\circ\text{C}$
    - Giá của một món đồ: $49.95$

    => Những con số riêng đơn lẻ này chính là **scalar**.

### **1. Scalars in a Machine Learning Context**

- Trong **machine learning**, **scalar** xuất hình ở khắp nơi. Chúng thường được dùng để biểu diễn những giá trị đơn lẻ như:
    - **Feature value**: Tuổi của một người - `34`
    - **Hyperparameter**: learning rate của mô hình - `0.01`
    - **Measurement**: Độ sáng của một pixel trong ảnh grayscale - `182`
    - **Model** output: Xác suất dự đoán một sự kiện - `0.87`

#### **1.1 Mathematical Symbols**

- Về mặt toán học, **scalar** thường được viết bằng:
    - Chữ cái thường in nghiêng: *$c, k, x, ...$*
    - Hoặc chữ cái Hy Lạp: $𝛂 (alpha), λ (lambda),...$
    - Vd: ta có thể định nghĩa một scalar *$s$* như sau:
        -  $s = 5$


<p align="center">
  <img src="../../Images/Gemini_Generated_Image_2fkm242fkm242fkm.png" alt="Gemini_Generated_Image_2fkm242fkm242fkm.png"/>
</p>

### **2. Representing Scalars in Python**

- Trong Python, **scalar** được biển diễn bằng các kiểu dữ liệu số thông thường: `int, float`.

In [ ]:
# An integer scalar
sample_count = 150

# A floating-point scalar
learning_rate = 0.001

# Another scalar representing a model parameter
bias_term = -2.5

print(f"Sample count: {sample_count} (Type: {type(sample_count)})")
print(f"Learning rate: {learning_rate} (Type: {type(learning_rate)})")

Sample count: 150 (Type: <class 'int'>)
Learning rate: 0.001 (Type: <class 'float'>)


### **3. Relationship between Scalars and Vectors**

- **Scalars** là các thành phần cấu tạo nên **Vectors**. Một vector $v$ trong không gian $n$ chiều thực chất là một danh sách gồm $n$ scalars.
- **Scalar Multiplication**: Đây là phép toán quan trọng nhất thể hiện mối quan hệ giữa chúng. Khi nhân một scalar $k$ với một vector $v$, mỗi phần tử trong vector sẽ được nhân với $k$. Điều này làm thay đổi độ lớn (magnitude) của vector nhưng giữ nguyên (hoặc đảo ngược) hướng của nó.

VD: Nếu bạn có một vector vận tốc, và bạn nhân nó với một scalar là 2, bạn đang gấp đôi tốc độ nhưng vẫn đi theo hướng cũ.

In [ ]:
import numpy as np

# Define a vector (a set of scalars).
vector = np.array([1, 2, 3])

# Define a scalar
scalar_k = 2

# Scalar multiplication by vector
scaled_vector = scalar_k * vector

print(f"Original Vector: {vector}")
print(f"Scalar: {scalar_k}")
print(f"Scaled Vector (k * v): {scaled_vector}")

Original Vector: [1 2 3]
Scalar: 2
Scaled Vector (k * v): [2 4 6]


### **4. Summary**

- Mặc dù **scalar rất đơn giản**, nhưng chúng là **những "nguyên tử" của dữ liệu**.
- Chúng ta sử dụng các scalar này để xây dựng các cấu trúc phức tạp hơn:
    - **Vector**: Một danh sách các scalars.
    - **Matrix**: Một bảng (grid) chứa các scalars.
- Trong Machine Learning, scalar đại diện cho các giá trị đơn lẻ như learning rate, giá trị đặc trưng (feature value), hoặc trọng số (bias).
- Phép nhân scalar với vector cho thấy cách một giá trị đơn lẻ có thể tác động lên toàn bộ tập hợp dữ liệu bằng cách thay đổi độ lớn của chúng.